source "https://rubygems.org"

gem "rails", "<%= Rails.version %>"
gem "active_application"

group :development, :test do
  gem "capybara"
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "forgery"
  gem "guard-rspec"
  gem "guard-spork"
  gem "launchy"
  gem "rb-inotify"
  gem "rspec-rails"
  gem "shoulda-matchers"
  gem "spork-rails"
  gem "sqlite3"
end

group :development do
  gem "capistrano"
end

group :production do
  gem "exception_notification_rails3", require: "exception_notifier"
  gem "mysql2"
end

group :assets do
  gem "coffee-rails", "~> 3.2.1"
  gem "sass-rails", "~> 3.2.3"
  gem "therubyracer", "~> 0.10.2"
  gem "uglifier", ">= 1.0.3"
end
