source "https://rubygems.org"

gem "rails", "<%= Rails.version %>"
#gem "active_application", "0.0.1"
gem "active_application", path: "/home/jari/work/gems/active_application"

group :development, :test do
  gem "capybara", "~> 2.0.1"
  gem "database_cleaner", "~> 0.9.1"
  gem "factory_girl_rails", "~> 4.1.0"
  gem "forgery", "~> 0.5.0"
  gem "guard-rspec", "~> 2.3.0"
  gem "guard-spork", "~> 1.4.0"
  gem "launchy", "~> 2.1.2"
  gem "rb-inotify", "~> 0.8.8"
  gem "rspec-rails", "~> 2.12.0"
  gem "shoulda-matchers", "~> 1.4.2"
  gem "spork-rails", "~> 3.2.0"
  gem "sqlite3", "~> 1.3.6"
end

group :development do
  gem "capistrano", "~> 2.13.5"
end

group :production do
  gem "exception_notification_rails3", "~> 1.2.0", require: "exception_notifier"
  gem "mysql2", "~> 0.3.11"
end

group :assets do
  gem "coffee-rails", "~> 3.2.1"
  gem "sass-rails", "~> 3.2.3"
  gem "therubyracer", "~> 0.10.2"
  gem "uglifier", ">= 1.0.3"
end
